### ISSUE TITLE
JDK 8u102 is out

### ISSUE THREAD

**Issue by vbsessa** [tuxjdk/tuxjdk#20]
I know you're a busy guy and leads this project on your own, but i'd like to remember that a new version of JDK is available. No pressure! Rsrsrs

**Comment by TheIndifferent** [comment]
Please see the better maintained project from @JetBrains: https://dl.bintray.com/jetbrains/intellij-jdk/

As far as I can see, they've implemented similar functionality but in cross-platform manner, so it is possible that I will be trying to contribute to their fork instead of trying to fix the world myself.

**Comment by vbsessa** [comment]
Ohhh i see. Good to hear that a big player has noticed it then.
